### ISSUE TITLE
Example Run Failure: trigger_scan

### ISSUE THREAD

**Issue by ThisSeanZhang** [rust-netlink/wl-nl80211#22]
I tried to run the example on my M28K board, but I am confused by the results.
This is my first time writing similar code, so please let me know if there are any issues or if I can improve in any way. I appreciate your feedback!

## sys info
```text
Distributor ID: Debian
Description:    Armbian-unofficial 24.11.0-trunk bookworm
Release:        12
Codename:       bookworm

Linux mangopi-m28k 6.1.75-vendor-rk35xx #1 SMP Sat Aug 17 03:40:42 UTC 2024 aarch64 GNU/Linux

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
```

## dump_nl80211_iface
```shell
cargo run --package wl-nl80211 --example dump_nl80211_iface
```
result: 
```text
GenlMessage { 
  header: GenlHeader { cmd: 7, version: 1 },
  payload: Nl80211Message { 
    cmd: NewInterface, 
    attributes: [IfIndex(4), IfName("wlan0"), Wiphy(0), IfType(Station), Wdev(1), Mac([.......]), Generation(5), Use4Addr(false)]
  }, 
  resolved_family_id: 28
}
```
##  nl80211_trigger_scan
```shell
RUST_BACKTRACE=1 cargo run --package wl-nl80211 --example nl80211_trigger_scan 4
```
result: 
```text
HAHA offset 25
HAHA offset 25
HAHA offset 25
HAHA offset 25
thread 'main' panicked at examples/nl80211_trigger_scan.rs:48:49:
called `Result::unwrap()` on an `Err` value: Bug("BUG: decode error DecodeError { inner: Failed to parse nl80211 message attribute\n\nCaused by:\n    Decode error occurred: Invalid length of Nl80211Element [0, 0]\n\nStack backtrace:\n   0: std::backtrace_rs::backtrace::libunwind::trace\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5\n   1: std::backtrace_rs::backtrace::trace_unsynchronized\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5\n   2: std::backtrace::Backtrace::create\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/backtrace.rs:331:13\n   3: <E as anyhow::context::ext::StdError>::ext_context\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/backtrace.rs:27:14\n   4: anyhow::context::<impl anyhow::Context<T,E> for core::result::Result<T,E>>::context\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.89/src/context.rs:54:31\n   5: wl_nl80211::message::parse_nlas\n             at ./src/message.rs:46:19\n   6: <wl_nl80211::message::Nl80211Message as netlink_packet_utils::traits::ParseableParametrized<[u8],netlink_packet_generic::header::GenlHeader>>::parse_with_param\n             at ./src/message.rs:57:26\n   7: genetlink::message::RawGenlMessage::parse_into_genlmsg\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/genetlink-0.2.5/src/message.rs:79:21\n   8: genetlink::message::map_from_rawgenlmsg\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/genetlink-0.2.5/src/message.rs:183:42\n   9: core::ops::function::FnMut::call_mut\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/ops/function.rs:166:5\n  10: <T as futures_util::fns::FnMut1<A>>::call_mut\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/fns.rs:28:9\n  11: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:59:33\n  12: core::option::Option<T>::map\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/option.rs:1105:29\n  13: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:59:21\n  14: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/stream/map.rs:58:26\n  15: <futures_util::future::either::Either<A,B> as futures_core::stream::Stream>::poll_next\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/future/either.rs:137:32\n  16: <S as futures_core::stream::TryStream>::try_poll_next\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-core-0.3.30/src/stream.rs:196:9\n  17: futures_util::stream::try_stream::TryStreamExt::try_poll_next_unpin\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/try_stream/mod.rs:1131:9\n  18: <futures_util::stream::try_stream::try_next::TryNext<St> as core::future::future::Future>::poll\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.30/src/stream/try_stream/try_next.rs:32:9\n  19: nl80211_trigger_scan::dump_scan::{{closure}}\n             at ./examples/nl80211_trigger_scan.rs:48:43\n  20: <core::pin::Pin<P> as core::future::future::Future>::poll\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/future/future.rs:123:9\n  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57\n  22: tokio::runtime::coop::with_budget\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5\n  23: tokio::runtime::coop::budget\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5\n  24: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25\n  25: tokio::runtime::scheduler::current_thread::Context::enter\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19\n  26: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36\n  27: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68\n  28: tokio::runtime::context::scoped::Scoped<T>::set\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9\n  29: tokio::runtime::context::set_scheduler::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26\n  30: std::thread::local::LocalKey<T>::try_with\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/thread/local.rs:283:12\n  31: std::thread::local::LocalKey<T>::with\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/thread/local.rs:260:9\n  32: tokio::runtime::context::set_scheduler\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9\n  33: tokio::runtime::scheduler::current_thread::CoreGuard::enter\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27\n  34: tokio::runtime::scheduler::current_thread::CoreGuard::block_on\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19\n  35: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28\n  36: tokio::runtime::context::runtime::enter_runtime\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16\n  37: tokio::runtime::scheduler::current_thread::CurrentThread::block_on\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9\n  38: tokio::runtime::runtime::Runtime::block_on_inner\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47\n  39: tokio::runtime::runtime::Runtime::block_on\n             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13\n  40: nl80211_trigger_scan::main\n             at ./examples/nl80211_trigger_scan.rs:24:5\n  41: core::ops::function::FnOnce::call_once\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/ops/function.rs:250:5\n  42: std::sys::backtrace::__rust_begin_short_backtrace\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/sys/backtrace.rs:154:18\n  43: std::rt::lang_start::{{closure}}\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/rt.rs:164:18\n  44: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/ops/function.rs:284:13\n  45: std::panicking::try::do_call\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:554:40\n  46: std::panicking::try\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:518:19\n  47: std::panic::catch_unwind\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panic.rs:345:14\n  48: std::rt::lang_start_internal::{{closure}}\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/rt.rs:143:48\n  49: std::panicking::try::do_call\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:554:40\n  50: std::panicking::try\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:518:19\n  51: std::panic::catch_unwind\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panic.rs:345:14\n  52: std::rt::lang_start_internal\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/rt.rs:143:20\n  53: std::rt::lang_start\n             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/rt.rs:163:17\n  54: main\n  55: <unknown>\n  56: __libc_start_main\n  57: _start }")
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/panicking.rs:662:5
   1: core::panicking::panic_fmt
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/result.rs:1102:23
   4: nl80211_trigger_scan::dump_scan::{{closure}}
             at ./examples/nl80211_trigger_scan.rs:48:27
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/future/future.rs:123:9
   6: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:57
   7: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/coop.rs:73:5
   9: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:696:25
  10: tokio::runtime::scheduler::current_thread::Context::enter
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:423:19
  11: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:695:36
  12: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:68
  13: tokio::runtime::context::scoped::Scoped<T>::set
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/scoped.rs:40:9
  14: tokio::runtime::context::set_scheduler::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:26
  15: std::thread::local::LocalKey<T>::try_with
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/thread/local.rs:283:12
  16: std::thread::local::LocalKey<T>::with
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/std/src/thread/local.rs:260:9
  17: tokio::runtime::context::set_scheduler
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context.rs:180:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:774:27
  19: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:683:19
  20: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:191:28
  21: tokio::runtime::context::runtime::enter_runtime
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/context/runtime.rs:65:16
  22: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/scheduler/current_thread/mod.rs:179:9
  23: tokio::runtime::runtime::Runtime::block_on_inner
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:361:47
  24: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.40.0/src/runtime/runtime.rs:335:13
  25: nl80211_trigger_scan::main
             at ./examples/nl80211_trigger_scan.rs:24:5
  26: core::ops::function::FnOnce::call_once
             at /rustc/6de928dce9472b864f4e5d590dd7aa2075cb7551/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If you need any more information, please feel free to let me know. Thank you!

**Comment by ThisSeanZhang** [comment]
iw list info
```text
iw list
Wiphy phy0
        wiphy index: 0
        max # scan SSIDs: 3
        max scan IEs length: 200 bytes
        max # sched scan SSIDs: 0
        max # match sets: 0
        Retry short limit: 7
        Retry long limit: 4
        Coverage class: 0 (up to 0m)
        Device supports RSN-IBSS.
        Device supports AP-side u-APSD.
        Supported Ciphers:
                * WEP40 (00-0f-ac:1)
                * WEP104 (00-0f-ac:5)
                * TKIP (00-0f-ac:2)
                * CCMP-128 (00-0f-ac:4)
                * CMAC (00-0f-ac:6)
                * WPI-SMS4 (00-14-72:1)
        Available Antennas: TX 0 RX 0
        Supported interface modes:
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * P2P-device
        Band 1:
                Capabilities: 0x963
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 1-stream
                        Max AMSDU length: 7935 bytes
                        No DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 150 Mbps
                HT TX/RX MCS rate indexes supported: 0-7, 32
                VHT Capabilities (0x03987132):
                        Max MPDU length: 11454
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        SU Beamformee
                        MU Beamformer
                        MU Beamformee
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: not supported
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 390 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: not supported
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 390 Mbps
                VHT extended NSS: not supported
                HE Iftypes: managed, AP
                        HE MAC Capabilities (0x000000020000):
                                All Ack
                        HE PHY Capabilities: (0x06e02b580dc0cf04023000):
                                HE40/2.4GHz
                                HE40/HE80/5GHz
                                LDPC Coding in Payload
                                HE SU PPDU with 1x HE-LTF and 0.8us GI
                                Midamble Rx Max NSTS: 3
                                NDP with 4x HE-LTF and 3.2us GI
                                STBC Rx <= 80MHz
                                Doppler Rx
                                DCM Max Constellation Rx: 3
                                Rx HE MU PPDU from Non-AP STA
                                SU Beamformee
                                Beamformee STS <= 80Mhz: 3
                                Ng = 16 SU Feedback
                                Ng = 16 MU Feedback
                                Codebook Size SU Feedback
                                Codebook Size MU Feedback
                                Triggered SU Beamforming Feedback
                                Triggered MU Beamforming Feedback
                                Partial Bandwidth DL MU-MIMO
                                PPE Threshold Present
                                HE SU PPDU & HE PPDU 4x HE-LTF 0.8us GI
                                20MHz in 40MHz HE PPDU 2.4GHz
                                RX Full BW SU Using HE MU PPDU with Compression SIGB
                                RX Full BW SU Using HE MU PPDU with Non-Compression SIGB
                        HE RX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: not supported
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: not supported
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        PPE Threshold 0x38 0x1c 0xc7 0x07 
                EHT Iftypes: managed, AP
                        EHT MAC Capabilities (0x0000):
                        EHT PHY Capabilities: (0x0000000000000000):
                        EHT MCS/NSS: (0x):
                        EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                Bitrates (non-HT):
                        * 1.0 Mbps
                        * 2.0 Mbps (short preamble supported)
                        * 5.5 Mbps (short preamble supported)
                        * 11.0 Mbps (short preamble supported)
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 2412 MHz [1] (20.0 dBm)
                        * 2417 MHz [2] (20.0 dBm)
                        * 2422 MHz [3] (20.0 dBm)
                        * 2427 MHz [4] (20.0 dBm)
                        * 2432 MHz [5] (20.0 dBm)
                        * 2437 MHz [6] (20.0 dBm)
                        * 2442 MHz [7] (20.0 dBm)
                        * 2447 MHz [8] (20.0 dBm)
                        * 2452 MHz [9] (20.0 dBm)
                        * 2457 MHz [10] (20.0 dBm)
                        * 2462 MHz [11] (20.0 dBm)
                        * 2467 MHz [12] (20.0 dBm)
                        * 2472 MHz [13] (20.0 dBm)
                        * 2484 MHz [14] (20.0 dBm)
        Band 2:
                Capabilities: 0x963
                        RX LDPC
                        HT20/HT40
                        Static SM Power Save
                        RX HT20 SGI
                        RX HT40 SGI
                        RX STBC 1-stream
                        Max AMSDU length: 7935 bytes
                        No DSSS/CCK HT40
                Maximum RX AMPDU length 65535 bytes (exponent: 0x003)
                Minimum RX AMPDU time spacing: 16 usec (0x07)
                HT Max RX data rate: 150 Mbps
                HT TX/RX MCS rate indexes supported: 0-7, 32
                VHT Capabilities (0x03987132):
                        Max MPDU length: 11454
                        Supported Channel Width: neither 160 nor 80+80
                        RX LDPC
                        short GI (80 MHz)
                        SU Beamformee
                        MU Beamformer
                        MU Beamformee
                VHT RX MCS set:
                        1 streams: MCS 0-9
                        2 streams: not supported
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT RX highest supported: 390 Mbps
                VHT TX MCS set:
                        1 streams: MCS 0-9
                        2 streams: not supported
                        3 streams: not supported
                        4 streams: not supported
                        5 streams: not supported
                        6 streams: not supported
                        7 streams: not supported
                        8 streams: not supported
                VHT TX highest supported: 390 Mbps
                VHT extended NSS: not supported
                HE Iftypes: managed, AP
                        HE MAC Capabilities (0x000000020000):
                                All Ack
                        HE PHY Capabilities: (0x06e02b580dc0cf04023000):
                                HE40/2.4GHz
                                HE40/HE80/5GHz
                                LDPC Coding in Payload
                                HE SU PPDU with 1x HE-LTF and 0.8us GI
                                Midamble Rx Max NSTS: 3
                                NDP with 4x HE-LTF and 3.2us GI
                                STBC Rx <= 80MHz
                                Doppler Rx
                                DCM Max Constellation Rx: 3
                                Rx HE MU PPDU from Non-AP STA
                                SU Beamformee
                                Beamformee STS <= 80Mhz: 3
                                Ng = 16 SU Feedback
                                Ng = 16 MU Feedback
                                Codebook Size SU Feedback
                                Codebook Size MU Feedback
                                Triggered SU Beamforming Feedback
                                Triggered MU Beamforming Feedback
                                Partial Bandwidth DL MU-MIMO
                                PPE Threshold Present
                                HE SU PPDU & HE PPDU 4x HE-LTF 0.8us GI
                                20MHz in 40MHz HE PPDU 2.4GHz
                                RX Full BW SU Using HE MU PPDU with Compression SIGB
                                RX Full BW SU Using HE MU PPDU with Non-Compression SIGB
                        HE RX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: not supported
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        HE TX MCS and NSS set <= 80 MHz
                                1 streams: MCS 0-11
                                2 streams: not supported
                                3 streams: not supported
                                4 streams: not supported
                                5 streams: not supported
                                6 streams: not supported
                                7 streams: not supported
                                8 streams: not supported
                        PPE Threshold 0x38 0x1c 0xc7 0x07 
                EHT Iftypes: managed, AP
                        EHT MAC Capabilities (0x0000):
                        EHT PHY Capabilities: (0x0000000000000000):
                        EHT MCS/NSS: (0x):
                        EHT bw <= 80 MHz, max NSS for MCS 8-9: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 10-11: Rx=0, Tx=0
                        EHT bw <= 80 MHz, max NSS for MCS 12-13: Rx=0, Tx=0
                Bitrates (non-HT):
                        * 6.0 Mbps
                        * 9.0 Mbps
                        * 12.0 Mbps
                        * 18.0 Mbps
                        * 24.0 Mbps
                        * 36.0 Mbps
                        * 48.0 Mbps
                        * 54.0 Mbps
                Frequencies:
                        * 5180 MHz [36] (20.0 dBm)
                        * 5200 MHz [40] (20.0 dBm)
                        * 5220 MHz [44] (20.0 dBm)
                        * 5240 MHz [48] (20.0 dBm)
                        * 5260 MHz [52] (20.0 dBm)
                        * 5280 MHz [56] (20.0 dBm)
                        * 5300 MHz [60] (20.0 dBm)
                        * 5320 MHz [64] (20.0 dBm)
                        * 5500 MHz [100] (20.0 dBm)
                        * 5520 MHz [104] (20.0 dBm)
                        * 5540 MHz [108] (20.0 dBm)
                        * 5560 MHz [112] (20.0 dBm)
                        * 5580 MHz [116] (20.0 dBm)
                        * 5600 MHz [120] (20.0 dBm)
                        * 5620 MHz [124] (20.0 dBm)
                        * 5640 MHz [128] (20.0 dBm)
                        * 5660 MHz [132] (20.0 dBm)
                        * 5680 MHz [136] (20.0 dBm)
                        * 5700 MHz [140] (20.0 dBm)
                        * 5720 MHz [144] (20.0 dBm)
                        * 5745 MHz [149] (20.0 dBm)
                        * 5765 MHz [153] (20.0 dBm)
                        * 5785 MHz [157] (20.0 dBm)
                        * 5805 MHz [161] (20.0 dBm)
                        * 5825 MHz [165] (20.0 dBm)
        Supported commands:
                 * new_interface
                 * set_interface
                 * new_key
                 * start_ap
                 * new_station
                 * new_mpath
                 * set_mesh_config
                 * set_bss
                 * join_mesh
                 * remain_on_channel
                 * frame
                 * set_channel
                 * probe_client
                 * register_beacons
                 * start_p2p_device
                 * connect
                 * disconnect
                 * channel_switch
                 * update_ft_ies
        WoWLAN support:
                 * wake up on anything (device continues operating normally)
                 * wake up on magic packet
        software interface modes (can always be added):
        valid interface combinations:
                 * #{ managed, mesh point } <= 1, #{ AP } <= 1, #{ P2P-client, P2P-GO } <= 1, #{ P2P-device } <= 1,
                   total <= 4, #channels <= 3
        Device supports TX status socket option.
        Device supports SAE with AUTHENTICATE command
        Device supports scan flush.
        Device supports per-vif TX power setting
        Userspace should do OBSS scan and generate 20/40 coex reports
        Driver supports a userspace MPM
        Device supports active monitor (which will ACK incoming frames)
        Driver/device bandwidth changes during BSS lifetime (AP/GO mode)
        max # scan plans: 1
        max scan plan interval: -1
        max scan plan iterations: 0
        Supported TX frame types:
                 * managed: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * AP/VLAN: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * mesh point: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-client: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-GO: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
                 * P2P-device: 0x00 0x10 0x20 0x30 0x40 0x50 0x60 0x70 0x80 0x90 0xa0 0xb0 0xc0 0xd0 0xe0 0xf0
        Supported RX frame types:
                 * managed: 0x40 0xb0 0xd0
                 * AP: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * AP/VLAN: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * mesh point: 0xb0 0xc0 0xd0
                 * P2P-client: 0x40 0xd0
                 * P2P-GO: 0x00 0x20 0x40 0xa0 0xb0 0xc0 0xd0
                 * P2P-device: 0x40 0xd0
        Supported extended features:
```
